version: "3"
services:
  rxnmapper_service:
    build:
      context: .
      dockerfile: dev.dockerfile
    container_name: rxnmapper_service_dev
    image: rxnmapper_service_dev
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    restart: always
    ports:
    - "8001:8002" # HOST:CONTAINER
    volumes:
      - ./src:/code/src # useful in dev

